Repository 4JOCHAMCHI/YAGUROUTE, pull requests merged in 2024-08, with the labels that each got.

#79 [Feat] Kafka DLQ 추가한 이메일 발송 기능
  yagu-route/src/main/java/org/teamtuna/yaguroute/config/KafkaConfig.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/dto/MailDTO.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/GameSeatService.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/MailService.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/TicketService.java
Labels: feature

#82 [Feat] 팀 로고 설정 및 조회 + 경기좌석 자동생성 및 삭제,업데이트 메소드 구현
  yagu-route/build.gradle
  yagu-route/src/main/java/org/teamtuna/yaguroute/YaguRouteApplication.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/GameSeat.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/config/DataInitializer.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/config/GoogleCloudStorageConfig.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/TeamController.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/repository/GameRepository.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/repository/GameSeatRepository.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/repository/SeatRepository.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/repository/TeamRepository.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/repository/TicketRepository.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/GameServiceImpl.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/TeamService.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/TeamServiceImpl.java
Labels: feature

#87 [Refactor] service-serviceImpl 구조로 변경
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/GameSeatService.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/GameSeatServiceImpl.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/MemberService.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/TicketService.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/TicketServiceImpl.java
Labels: refactor

#92 build.gradle 파일 정리
  yagu-route/build.gradle
Labels: docs

#94 [Refactor] Swagger 구문 추가
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/GameController.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/TeamController.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/TeamRankController.java
Labels: refactor

#95 [Docs] Swagger 구문 추가
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/GameSeatController.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/TicketController.java
Labels: docs

#96 [Docs] Swagger 구문 추가
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/MemberController.java
Labels: docs

#113 [Test] 테스트 코드 추가
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/GameSeatService.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/GameSeatServiceImpl.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/TicketServiceImpl.java
  yagu-route/src/test/java/org/teamtuna/yaguroute/service/GameSeatServiceTest.java
Labels: refactor, test

#125 [Test] MemberService 테스트 코드 추가
  yagu-route/src/test/java/org/teamtuna/yaguroute/service/MemberServiceTest.java
Labels: test

#126 [Test] GameService 테스트 코드 추가 + [Refactor] Update GameServiceImpl
  yagu-route/build.gradle
  yagu-route/src/main/java/org/teamtuna/yaguroute/repository/GameSeatRepository.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/GameServiceImpl.java
  yagu-route/src/test/java/org/teamtuna/yaguroute/service/GameServiceImplTest.java
  yagu-route/src/test/resources/application-test.yml
  yagu-route/src/test/resources/data.sql
  yagu-route/src/test/resources/schema.sql
Labels: refactor, test

#139 [Fix] 좌석 조회 관련 메소드 수정
  yagu-route/src/main/java/org/teamtuna/yaguroute/config/WebConfig.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/GameSeatController.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/repository/GameSeatRepository.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/repository/SeatRepository.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/GameSeatService.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/GameSeatServiceImpl.java
  yagu-route/src/test/java/org/teamtuna/yaguroute/service/GameSeatServiceTest.java
Labels: feature, fix, test

#142 Refactor: Update Game
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/GameController.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/dto/GameSummaryDTO.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/dto/TeamRankDTO.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/repository/GameRepository.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/GameService.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/GameServiceImpl.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/TeamRankServiceImpl.java
Labels: refactor

#144 Feat: Add TeamName by GameId
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/GameController.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/dto/GameTeamDTO.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/GameService.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/GameServiceImpl.java
Labels: feature

#145 [ Feat] 로그인 한 사용자 정보 관련 기능 추가
  yagu-route/src/main/java/org/teamtuna/yaguroute/config/security/SecurityConfig.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/AuthController.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/ProfileController.java
  yagu-route/src/test/java/org/teamtuna/yaguroute/service/MemberServiceTest.java
Labels: feature

#150 [Feat] 로그인 관련 기능 구현 추가
  .github/workflows/gradle.yml
  yagu-route/Dockerfile
  yagu-route/build.gradle
  yagu-route/src/main/java/org/teamtuna/yaguroute/config/security/AjaxAuthenticationEntryPoint.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/config/security/SecurityConfig.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/AuthController.java
Labels: feature
