Repository 4JOCHAMCHI/YAGUROUTE, pull requests merged in 2024-07, with the labels that each got.

#44 [Feat] Kafka 클러스터 생성
  yagu-route/build.gradle
  yagu-route/compose.yaml
  yagu-route/src/main/java/org/teamtuna/yaguroute/YaguRouteApplication.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Team.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/BookingController.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/dto/TeamDTO.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/repository/TeamRepository.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/MailService.java
Labels: feature

#46 [Feat] Redis 클러스터 생성
  yagu-route/build.gradle
  yagu-route/compose.yaml
  yagu-route/config/redis/redis0.conf
  yagu-route/config/redis/redis1.conf
  yagu-route/config/redis/redis2.conf
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/RedisTestController.java
Labels: feature

#47 [Feat] 이메일 발송 기능 구현, JPA 엔티티 클래스 추가
  yagu-route/build.gradle
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Booking.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Game.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Member.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Team.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Ticket.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/MailService.java
Labels: feature, fix

#54 [Feat] 회원 전체 조회, 회원 상세 정보 조회 기능 구현
  yagu-route/build.gradle
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Member.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/config/BeanConfig.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/MemberController.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/dto/MemberDTO.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/repository/MemberRepository.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/MemberService.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/MemberServiceImpl.java
Labels: feature

#61 [Refactor] ERD 수정에 따른 JPA 엔티티 클래스 수정
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Booking.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Game.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Member.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Sellable.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Team.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Ticket.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/dto/BookingDTO.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/dto/GameDTO.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/dto/TicketDTO.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/repository/TicketRepository.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/TicketService.java
Labels: refactor

#63 [Feat] 특정조건 조회 RequestParam으로 변경
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Game.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Team.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/GameController.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/TeamRankController.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/repository/GameRepository.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/GameServiceImpl.java
Labels: refactor

#65 [Feat] 경기 상세 정보 + location, stadium 정보 조회 메소드 구현
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/GameController.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/dto/GameDetailDTO.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/repository/GameRepository.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/GameService.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/GameServiceImpl.java
Labels: feature

#69 [Feat] 좌석 조회 기능 구현
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Booking.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Game.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Member.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Team.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/TeamRank.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/aggregate/Ticket.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/common/ResponseMessage.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/controller/TicketController.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/dto/BookingDTO.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/dto/TicketDTO.java
  yagu-route/src/main/java/org/teamtuna/yaguroute/service/TicketService.java
Labels: feature, fix
